### ISSUE TITLE
SDK kucoin-python to support .io API host

### ISSUE THREAD

**Issue by qhxin** [Kucoin-academy/Guide#9]
When i debug at local env, i got some errors like:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openapi-sandbox.kucoin.com', port=443): Max retries exceeded with url: /api/v1/market/orderbook/level1?symbol=BTC-USDT (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f43bb8da9b0>, 'Connection to openapi-sandbox.kucoin.com timed out. (connect timeout=5)'))


```
So, How about to support `openapi-sandbox.kucoin.io` in `kucoin-python` ?

**Comment by 1bazinga25** [comment]
Hi there,now `kucoin-python` SDK can set host url by yourself. Use as follows:
```
pip install kucoin-python==0.1.2
```
Please ensure you have update your `kucoin-python` SDK to version `0.1.2`.
Then if you want to set the host url:
```
client = User(api_key, api_secret, api_passphrase, url='https://openapi-sandbox.kucoin.io')
```
I think it can solve your problems.

**Comment by NicoleQiujuan** [comment]
Hi, there
 May I know if you will keep updating the strategy?
